### ISSUE TITLE
Add github action to run tests

### ISSUE THREAD

**Issue by westonplatter** [jkirkby3/fypy#5]
Came across this library and wanted to see @jkirkby3 if you open to having the test suite run via Github Actions. For example, https://github.com/westonplatter/finx-reports-ib/blob/main/.github/workflows/ci.yml. The end goal being that on each pull request / commit to master would kick off a Github test suite run.

If you're open to it, I can start adding it.

**Comment by jkirkby3** [comment]
@westonplatter, that would be great, thanks for offering. Please let me know if you need anything from me

**Comment by westonplatter** [comment]
@jkirkby3 sweet. I'll need to make changes the how normal and test specific python dependencies are handled. I'll get a working setup CI/CD going on my fork and then come back with questions.

**Comment by westonplatter** [comment]
Pull request with updates to run tests on github, https://github.com/jkirkby3/fypy/pull/8

**Comment by westonplatter** [comment]
Closing with the merge of #8
